core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path

from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='home'),
    path('customer/<str:uid>', views.open_customer, name='open_customer'),
    path('customer/add-record/<str:uid>', views.add_record, name='add_record')
]

main_app/models.py
from django.db import models
import uuid

# Create your models here.
class Customer(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    full_name = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=30)
    address = models.CharField(max_length=250, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.full_name
    
    class Meta:
        ordering = ('-created',)

class Purchase(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=250)
    item_qnty = models.IntegerField()
    item_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.customer}'

    

main_app/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)

from .models import (
    Customer,
    Purchase
)
# Create your views here.
def index(request):
    data = Customer.objects.all()
    context = {
        'title': 'Customer List',
        'data': data,
    }
    return render(request, 'main_app/index.html', context)

def open_customer(request, uid):
    data = Customer.objects.get(uid=uid)
    context = {
        'title': f'{data.full_name}',
        'data': data,
    }
    return render(request, 'main_app/open_customer.html', context)

@csrf_exempt
def add_record(request, uid):
    data = Customer.objects.get(uid=uid)
    if request.method == 'POST':
        jsn_data = json.loads(request.body)
        table_data = jsn_data.get('table_data', [])
        for row in table_data:
            item_name = row.get('item_name', [])
            item_qnty = row.get('item_qnty', [])
            item_price = row.get('item_price', [])
            entry = Purchase(
                customer=data,
                item_name=item_name,
                item_qnty=int(item_qnty) if item_qnty else 0,
                item_price=int(item_price) if item_price else 0,
            )
            entry.save()
    context = {
        'title': f'{data.full_name} | Add new purchase record',
        'data': data,
    }
    return render(request, 'main_app/add_new_record.html', context)

main_app/templates/main_app/add_new_record.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block body %}
<main>
    <div class="container mt-5">
        <div class="row row-cols-2 row-cols-lg-2">
            <div class="col">
                <h5 class="text-muted">{{data.full_name}} | New Purchase Records</h5>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div id="excel-form"></div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="button" class="btn btn-primary rounded-0" id="save-btn">Save purchase</button>
            </div>
        </div>
    </div>
</main>
<script src="{% static 'main_app/js/excel-form.js' %}"></script>
<script src="{% static 'main_app/js/axios.min.js' %}"></script>

<script>
    function saveData(){
        const table = document.getElementById('excel-table');
        const rows = table.getElementsByTagName('tr');
        const tableData = [];
        for (const row of rows){
            const cells = row.getElementsByTagName('td');
            const rowData = {};
            for (const cell of cells){
                const fieldName = cell.getAttribute('data-field');
                const value = cell.textContent.trim();
                if (value !== ''){
                    rowData[fieldName] = value;
                }
            }
            if (Object.keys(rowData).length > 0){
                tableData.push(rowData);
            }
        };
        axios.post("{% url 'main_app:add_record' data.uid %}", {
            table_data: tableData,

        }).then(
            response => {
                window.location.href = '{% url "main_app:open_customer" data.uid %}';
            }
        ).catch(error => {
            console.log('Error', error);
        });
    };
    const saveBTN = document.getElementById('save-btn');
    saveBTN.addEventListener('click', saveData);
</script>
{% endblock body %}

main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main_app/bootstrap/css/bootstrap.min.css' %}">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Welcome Back</title>
    {% endif %}
</head>
<body>
    {% block body %}{% endblock body %}
    <script src="{% static 'main_app/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

main_app/templates/main_app/index.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block body %}
<main>
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#ID</th>
                            <th>Customer Name</th>
                            <th>Phone</th>
                            <th>Address</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dat in data %}
                        <tr>
                            <td>#{{dat.id}}</td>
                            <td><a href="{% url 'main_app:open_customer' dat.uid %}" class="link-primary">{{dat.full_name}}</a></td>
                            <td>{{dat.phone_number}}</td>
                            <td>{{dat.address}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock body %}

main_app/templates/main_app/open_customer.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block body %}
<main>
    <div class="container mt-5">
        <div class="row row-cols-2 row-cols-lg-2">
            <div class="col">
                <h5 class="text-muted">{{data.full_name}} | Purchase List</h5>
            </div>
            <div class="col d-flex align-items-center justify-content-end">
                <a href="{% url 'main_app:add_record' data.uid %}" class="btn btn-primary rounded-0">Add New Record</a>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#ID</th>
                            <th>Item Name</th>
                            <th>Items Qnt</th>
                            <th>Item Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for dat in data.purchase_set.all %}
                        <tr>
                            <td>#{{dat.id}}</td>
                            <td>{{dat.item_name}}</td>
                            <td>{{dat.item_qnty}}</td>
                            <td>{{dat.item_price}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
{% endblock body %}